let data={orders:[],form:{}};
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL'}).format(n||0);
const date=s=>s?new Date(s+'T12:00').toLocaleDateString('pt-BR'):'';
async function api(url,opts={}){const r=await fetch(url,{headers:{'Content-Type':'application/json'},...opts});const j=await r.json();if(!r.ok)throw Error(j.error||'Não foi possível salvar');return j}
function progress(o){let q=0,x=0;(o.items||[]).forEach(i=>{q+=+i.quantidade;x+=+i.executado||0});return q?Math.min(100,Math.round(x/q*100)):0}
function row(o,full=false){const p=progress(o);return `<tr><td><span class="order-name">${o.numero}</span>${full?'':`<span class="sub">${o.local}</span>`}</td>${full?`<td>${o.contrato}</td><td>${o.local}</td><td>${date(o.recebida_em)}</td>`:`<td>${o.empresa||'Não atribuída'}</td>`}<td>${date(o.prazo)}</td>${full?`<td><span class="badge ${o.status==='Concluída'?'done':''}">${o.status}</span></td>`:`<td><span class="progress"><i style="width:${p}%"></i></span>${p}%</td><td>${money(o.total)}</td>`}<td><button class="text-btn" onclick="openDetail(${o.id})">Abrir →</button></td></tr>`}
async function load(){data=await api('/api/dashboard');data.form=await api('/api/form-data');document.querySelector('#active-count').textContent=data.cards.total;document.querySelector('#metric-open').textContent=data.cards.total;const first=data.orders.find(x=>x.status==='Em andamento');document.querySelector('#metric-deadline').textContent=first?date(first.prazo):'—';document.querySelector('#metric-place').textContent=first?first.local:'Sem OS abertas';document.querySelector('#metric-value').textContent=money(data.orders.filter(x=>x.status==='Em andamento').reduce((a,x)=>a+(x.total||0),0));renderDashboard();renderOrders();renderRegistry()}
function renderDashboard(){const orders=data.orders.filter(x=>x.status==='Em andamento');document.querySelector('#dashboard-orders').innerHTML=orders.length?orders.map(o=>row(o)).join(''):'<tr><td colspan="6" class="empty">Nenhuma OS em andamento.</td></tr>';document.querySelector('#recent').innerHTML=data.recent.length?data.recent.map(x=>`<article><b>${x.os_numero} · Item ${x.codigo}</b>${x.quantidade} unidade(s) em ${date(x.executado_em)}<span class="sub">${x.observacao||'Sem observação'}</span></article>`).join(''):'<p>Nenhum lançamento ainda.</p>'}
function renderOrders(){let v=(document.querySelector('#search')?.value||'').toLowerCase(),s=document.querySelector('#status-filter')?.value||'';let os=data.orders.filter(o=>(!v||`${o.numero} ${o.local} ${o.empresa||''}`.toLowerCase().includes(v))&&(!s||o.status===s));document.querySelector('#all-orders').innerHTML=os.length?os.map(o=>row(o,true)).join(''):'<tr><td colspan="7" class="empty">Nenhuma ordem encontrada.</td></tr>'}
function renderRegistry(){let f=data.form;document.querySelector('#registry').innerHTML=[...f.empresas.map(x=>`<div class="registry-row"><span>EMPRESA</span><b>${x.nome}</b><small>${x.cnpj||''}</small></div>`),...f.consorcios.map(x=>`<div class="registry-row"><span>CONSÓRCIO</span><b>${x.nome}</b></div>`),...f.contratos.map(x=>`<div class="registry-row"><span>CONTRATO</span><b>${x.numero}</b><small>${x.consorcio}</small></div>`)].join('')}
function showPage(p){document.querySelectorAll('.page').forEach(x=>x.classList.toggle('active',x.id===p));document.querySelectorAll('nav button').forEach(x=>x.classList.toggle('active',x.dataset.page===p));let labels={dashboard:['PAINEL','Bom dia, equipe.'],orders:['OPERAÇÃO','Ordens de serviço'],structure:['CONFIGURAÇÃO','Cadastros do sistema']};breadcrumb.textContent=labels[p][0];title.textContent=labels[p][1]}
function modal(html){document.querySelector('#modal-root').innerHTML=`<div class="modal-back" onclick="if(event.target===this)closeModal()"><div class="modal">${html}</div></div>`}function closeModal(){document.querySelector('#modal-root').innerHTML=''}
function openOrderModal(){let f=data.form;modal(`<header><div><p class="eyebrow">NOVA ORDEM DE SERVIÇO</p><h2>Registrar OS recebida</h2></div><button class="close" onclick="closeModal()">×</button></header><form onsubmit="saveOrder(event)"><div class="form-grid"><label class="field">NÚMERO DA OS<input name="numero" required placeholder="Ex.: OS-2026-0188"></label><label class="field">CONTRATO<select name="contrato_id" required><option value="">Selecione</option>${f.contratos.map(x=>`<option value="${x.id}">${x.numero} — ${x.consorcio}</option>`)}</select></label><label class="field full">LOCAL / TRECHO<input name="local" required placeholder="Ex.: Av. Paulista, entre ruas X e Y"></label><label class="field">DATA DE RECEBIMENTO<input name="recebida_em" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label class="field">PRAZO DE EXECUÇÃO<input name="prazo" type="date" required></label><label class="field full">EMPRESA EXECUTORA<select name="empresa_id"><option value="">Definir depois</option>${f.empresas.map(x=>`<option value="${x.id}">${x.nome}</option>`)}</select></label></div><h3>Itens da OS</h3><div id="items"><div class="item-line"><input name="codigo" placeholder="Item" required><input name="descricao" placeholder="Descrição"><input name="quantidade" type="number" min="0" step=".01" placeholder="Qtd." required><input name="valor" type="number" min="0" step=".01" placeholder="R$ unit." required><button type="button" class="delete" onclick="this.parentElement.remove()">×</button></div></div><button type="button" class="text-btn" onclick="addItem()">+ Adicionar item</button><div class="modal-foot"><button class="outline" type="button" onclick="closeModal()">Cancelar</button><button class="primary">Salvar OS</button></div></form>`)}
function addItem(){document.querySelector('#items').insertAdjacentHTML('beforeend',`<div class="item-line"><input name="codigo" placeholder="Item" required><input name="descricao" placeholder="Descrição"><input name="quantidade" type="number" min="0" step=".01" placeholder="Qtd." required><input name="valor" type="number" min="0" step=".01" placeholder="R$ unit." required><button type="button" class="delete" onclick="this.parentElement.remove()">×</button></div>`)}
async function saveOrder(e){e.preventDefault();let f=new FormData(e.target),arr=k=>[...document.querySelectorAll(`[name=${k}]`)].map(x=>x.value),payload=Object.fromEntries(f);payload.itens=arr('codigo').map((x,i)=>({codigo:x,descricao:arr('descricao')[i],quantidade:+arr('quantidade')[i],valor_unitario:+arr('valor')[i]}));try{await api('/api/os',{method:'POST',body:JSON.stringify(payload)});closeModal();await load();showPage('orders')}catch(x){alert(x.message)}}
function openSimpleModal(kind){let content={empresa:`<label class="field full">NOME DA EMPRESA<input name="nome" required></label><label class="field full">CNPJ<input name="cnpj" placeholder="Opcional"></label>`,consorcio:`<label class="field full">NOME DO CONSÓRCIO<input name="nome" required></label><label class="field full">EMPRESAS PARTICIPANTES<select name="empresas" multiple size="${Math.min(5,data.form.empresas.length)}">${data.form.empresas.map(x=>`<option value="${x.id}">${x.nome}</option>`)}</select></label>`,contrato:`<label class="field">NÚMERO DO CONTRATO<input name="numero" required></label><label class="field">CONSÓRCIO<select name="consorcio_id" required>${data.form.consorcios.map(x=>`<option value="${x.id}">${x.nome}</option>`)}</select></label><label class="field full">OBJETO<input name="objeto" placeholder="Ex.: Manutenção viária"></label>`}[kind];modal(`<header><div><p class="eyebrow">CADASTRO</p><h2>Novo ${kind}</h2></div><button class="close" onclick="closeModal()">×</button></header><form onsubmit="saveSimple(event,'${kind}')"><div class="form-grid">${content}</div><div class="modal-foot"><button type="button" class="outline" onclick="closeModal()">Cancelar</button><button class="primary">Salvar</button></div></form>`)}
async function saveSimple(e,k){e.preventDefault();let f=new FormData(e.target),p=Object.fromEntries(f);if(k==='consorcio')p.empresas=[...e.target.querySelector('[name=empresas]').selectedOptions].map(x=>x.value);try{await api('/api/'+k,{method:'POST',body:JSON.stringify(p)});closeModal();await load()}catch(x){alert(x.message)}}
async function openDetail(id){let o=await api('/api/os/'+id);modal(`<header><div><p class="eyebrow">${o.numero} · ${o.status.toUpperCase()}</p><h2>${o.local}</h2></div><button class="close" onclick="closeModal()">×</button></header><div class="detail-meta"><div><span>Contrato</span><b>${o.contrato}</b></div><div><span>Executora</span><b>${o.empresa||'Não atribuída'}</b></div><div><span>Prazo</span><b>${date(o.prazo)}</b></div></div><h3>Controle de itens</h3><div class="table-wrap"><table><thead><tr><th>ITEM</th><th>PREVISTO</th><th>EXECUTADO</th><th>VALOR</th><th></th></tr></thead><tbody>${o.items.map(i=>`<tr><td><b>${i.codigo}</b><span class="sub">${i.descricao||''}</span></td><td>${i.quantidade}</td><td>${i.executado}</td><td>${money(i.quantidade*i.valor_unitario)}</td><td>${o.status!=='Concluída'?`<button class="text-btn" onclick="openPoint(${i.id},${id})">Lançar</button>`:''}</td></tr>`).join('')}</tbody></table></div><h3 style="margin-top:22px">Arquivos técnicos</h3><p style="font-size:12px;margin:4px 0 10px">PDF e DWG do projeto ficam guardados junto desta OS.</p>${o.attachments.length?`<div class="registry">${o.attachments.map(a=>`<div class="registry-row"><span>${a.tipo}</span><b>${a.nome_original}</b><small>Enviado em ${date(a.enviado_em)}</small></div>`).join('')}</div>`:'<p class="sub">Nenhum arquivo anexado.</p>'}<label class="outline" style="display:inline-block;margin-top:10px">+ Anexar PDF ou DWG<input type="file" accept=".pdf,.dwg" hidden onchange="uploadFile(this,${id})"></label><div class="detail-actions modal-foot">${o.status!=='Concluída'?`<button class="primary" onclick="finish(${id})">Marcar como concluída</button>`:'<span class="badge done">OS concluída</span>'}<button class="outline" onclick="closeModal()">Fechar</button></div>`)}
function openPoint(item,oid){modal(`<header><div><p class="eyebrow">LANÇAMENTO DIÁRIO</p><h2>Registrar produção</h2></div><button class="close" onclick="openDetail(${oid})">×</button></header><form onsubmit="savePoint(event,${oid})"><div class="form-grid"><label class="field">DATA<input name="executado_em" type="date" value="${new Date().toISOString().slice(0,10)}" required></label><label class="field">QUANTIDADE EXECUTADA<input name="quantidade" type="number" min=".01" step=".01" required></label><label class="field full">OBSERVAÇÃO<textarea name="observacao" rows="3" placeholder="Trecho, equipe ou observação relevante"></textarea></label></div><div class="modal-foot"><button class="outline" type="button" onclick="openDetail(${oid})">Cancelar</button><button class="primary">Salvar lançamento</button></div></form>`)}
async function savePoint(e,id){e.preventDefault();let p=Object.fromEntries(new FormData(e.target));p.os_item_id=id;p.quantidade=+p.quantidade;await api('/api/apontamentos',{method:'POST',body:JSON.stringify(p)});closeModal();await load()}
async function uploadFile(el,id){let f=el.files[0];if(!f)return;let b=await f.arrayBuffer();try{await api('/api/anexos',{method:'POST',body:JSON.stringify({os_id:id,nome:f.name,conteudo:btoa(String.fromCharCode(...new Uint8Array(b)))})});openDetail(id)}catch(x){alert(x.message)}}
async function finish(id){if(confirm('Confirmar a conclusão desta OS?')){await api(`/api/os/${id}/concluir`,{method:'POST',body:'{}'});closeModal();await load();showPage('orders')}}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>showPage(b.dataset.page));document.querySelector('#today').textContent=new Date().toLocaleDateString('pt-BR',{weekday:'long',day:'2-digit',month:'long'});load();
